name: Auto-generate Visuals

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas matplotlib

      - name: Run script to generate charts
        working-directory: ./src
        run: python main.py

      - name: Commit and push images
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add images/
          git commit -m "Update generated visuals" || echo "No changes to commit"
          git push
